ТЗ10
Lneheb/java-filmorate pull request #5
Opened 2023-03-03 11:38 UTC by Lneheb

2023-03-03 13:24 UTC, TomattmanYandex requested changes
Привет, есть что поправить

2023-03-03 13:24 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +    public ResponseEntity<Map<String,String>> handleFilmNotFound(FilmNotFoundException e) {
FilmNotFoundException и UserNotFoundException однотипны и обрабатываются одинаково, можно было бы сделать одну ошибку вместо двух, а детали проставлять в сообщении

2023-03-03 13:24 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public FilmController(FilmService filmService) {
лучше использовать аннотацию @RequiredArgsContructor
так если появится дополнительные зависимости все что надо будет, объявить новую переменную
 
а private FilmService filmService; надо сделать final

2023-03-03 13:24 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return filmService.createFilm(film);
Валидация должна быть на уровне контроллера

2023-03-03 13:24 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public List<Film> getMostPopularFilms(@RequestParam(defaultValue = "10") String count) {
количество должно быть опциональным

2023-03-03 13:24 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        Integer integerCount = Integer.parseInt(count);
можно сразу в параметрах метода указать что это будет числом, и не надо будет преобразовывать к числу

2023-03-03 13:24 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private UserService userService;
комменты будут теми же что и в предыдущем классе

2023-03-03 13:24 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public FilmService(ValidateFilmService validateFilmService, FilmStorage filmStorage, UserStorage userStorage) {
то же про инициализацию через конструктор что и выше

2023-03-03 13:24 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        film.setId(idCount);
id обычно проставляется на уровне хранилища

2023-03-03 13:24 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (!userStorage.containsUserId(userId)){
а проверить существует ли фильм?

2023-03-03 13:24 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +public class UserService {
тут то же что и в классе выше

2023-03-03 13:24 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        if (!films.containsKey(id)) {
лучше тут возвращать null или Optional.empty() а уже на уровне сервиса прокидывать ошибку

2023-03-03 13:24 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +public class InMemoryUserStorage implements UserStorage {
то же что и в классе выше

2023-03-03 14:34 UTC, Lneheb commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        Integer integerCount = Integer.parseInt(count);
Не получается defaultvalue сделать числом, выдает ошибку

2023-03-04 12:03 UTC, TomattmanYandex requested changes
Еще пару мелочей поправить

2023-03-04 12:03 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/exception/FilmOrUserNotFoundException.java
> +public class FilmOrUserNotFoundException extends RuntimeException {
Мoжно было бы назвать просто NotFoundException

2023-03-04 12:03 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +@RequiredArgsConstructor(onConstructor = @__(@Autowired))
(onConstructor = @__(@Autowired)) эта часть не обязательна, Spring умеет обрабатывать конструктор и без этой аннотации

2023-03-04 12:03 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        Integer integerCount = Integer.parseInt(count);
попробуй указать там строку "10" ведь все аргументы приходят как строки, а потом уже  в нужные типы преобразуются

2023-03-04 12:03 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +
как то много пустых строк

2023-03-04 12:03 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (!userStorage.containsUserId(userId) || !filmStorage.containsFilmId(id)){
тту можно не проверять фильм, все равно когда будешь вызывать getFilm эта проверка пройдет

2023-03-04 17:03 UTC, TomattmanYandex approved these changes
Принято

2023-03-05 14:02 UTC, merged